var proyectsDB = [

		{
			id: 0,
			name: 'Rekt4less',
			description: 'Tienda online de videojuegos con un sistema de venta random, ya está funcionando y generando ventas, necesitamos inversión para crecer.',
			currentMoney: 145000,
			goal: 145000,
			equity: 7,
			firstTime:'Fri May 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))', 
			endTime: 'Fri Jun 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))',
			followers: 5,
			category: 1,
			fondeado: true,
			image: 'proyectoImg1.jpg',
			video: '-6C5TZKwn2Q',
			following: true
		},
		{
			id: 1,
			name: 'Rekt4less',
			description: 'Tienda online de videojuegos con un sistema de venta random, ya está funcionando y generando ventas, necesitamos inversión para crecer.',
			currentMoney: 25000,
			goal: 296600,
			equity: 7,
			firstTime:'Fri May 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))', 
			endTime: 'Fri Jun 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))',
			followers: 5,
			category: 0,
			fondeado: false,
			image: 'proyectoImg1.jpg',
			video: 'fLBZFBS72XU',
			following: false
		},
		{
			id: 2,
			name: 'Rekt4less',
			description: 'Tienda online de videojuegos con un sistema de venta random, ya está funcionando y generando ventas, necesitamos inversión para crecer.',
			currentMoney: 100000,
			goal: 296600,
			equity: 7,
			firstTime:'Fri May 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))', 
			endTime: 'Fri Jun 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))',
			followers: 5,
			category: 2,
			fondeado: false,
			image: 'proyectoImg1.jpg',
			video: '-6C5TZKwn2Q',
			following: true
		},
		{
			id: 3,
			name: 'Rekt4less',
			description: 'Tienda online de videojuegos con un sistema de venta random, ya está funcionando y generando ventas, necesitamos inversión para crecer.',
			currentMoney: 90000,
			goal: 296600,
			equity: 7,
			firstTime:'Fri May 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))', 
			endTime: 'Fri Jun 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))',
			followers: 5,
			category: 3,
			fondeado: false,
			image: 'proyectoImg1.jpg',
			video: '-6C5TZKwn2Q',
			following: false
		},
		{
			id: 4,
			name: 'Rekt4less',
			description: 'Tienda online de videojuegos con un sistema de venta random, ya está funcionando y generando ventas, necesitamos inversión para crecer.',
			currentMoney: 89000,
			goal: 296600,
			equity: 7,
			firstTime:'Fri May 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))', 
			endTime: 'Fri Jun 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))',
			followers: 5,
			category: 3,
			fondeado: false,
			image: 'proyectoImg1.jpg',
			video: '-6C5TZKwn2Q',
			following: false
		},
		{
			id:5,
			name: 'Rekt4less',
			description: 'Tienda online de videojuegos con un sistema de venta random, ya está funcionando y generando ventas, necesitamos inversión para crecer.',
			currentMoney: 190000,
			goal: 296600,
			equity: 7,
			firstTime:'Fri May 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))', 
			endTime: 'Fri Jun 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))',
			followers: 10,
			category: 2,
			fondeado: false,
			image: 'proyectoImg1.jpg',
			video: '-6C5TZKwn2Q',
			following: true
		},
		{
			id: 6,
			name: 'Rekt4less',
			description: 'Tienda online de videojuegos con un sistema de venta random, ya está funcionando y generando ventas, necesitamos inversión para crecer.',
			currentMoney: 350000,
			goal: 350000,
			equity: 7,
			firstTime:'Fri May 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))', 
			endTime: 'Fri Jun 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))',
			followers: 5,
			category: 1,
			fondeado: true,
			image: 'proyectoImg1.jpg',
			video: '-6C5TZKwn2Q',
			following: false
		},
		{
			id: 7,
			name: 'Rekt4less',
			description: 'Tienda online de videojuegos con un sistema de venta random, ya está funcionando y generando ventas, necesitamos inversión para crecer.',
			currentMoney: 270000,
			goal: 296600,
			equity: 7,
			firstTime:'Fri May 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))', 
			endTime: 'Fri Jun 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))',
			followers: 5,
			category: 0,
			fondeado: false,
			image: 'proyectoImg1.jpg',
			video: '-6C5TZKwn2Q',
			following: false
		},
		{
			id: 8,
			name: 'Rekt4less',
			description: 'Tienda online de videojuegos con un sistema de venta random, ya está funcionando y generando ventas, necesitamos inversión para crecer.',
			currentMoney: 1000,
			goal: 296600,
			equity: 7,
			firstTime:'Fri May 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))', 
			endTime: 'Fri Jun 15 2016 14:25:16 GMT-0500 (Hora de verano central (México))',
			followers: 5,
			category: 0,
			fondeado: false,
			image: 'proyectoImg1.jpg',
			video: '-6C5TZKwn2Q',
			following: false
		}
			
	];




